###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "user-0",
  "password": "password-0"
}

### 올바른 비밀번호 변경 요청
PUT http://localhost:8080/api/v1/account/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyLTAiLCJleHAiOjE3MDY3MDg4NTN9.PrWRaMnOGLJSdkC6nfT1XXSfMyznHHA1oeCeaxd9ItI

{
  "oldPassword": "password-0",
  "newPassword": "password-0000"
}

### 기존 비밀번호와 새로운 비밀번호가 동일함
PUT http://localhost:8080/api/v1/account/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyLTAiLCJleHAiOjE3MDY3MDg4NTN9.PrWRaMnOGLJSdkC6nfT1XXSfMyznHHA1oeCeaxd9ItI

{
  "oldPassword": "password-0000",
  "newPassword": "password-0000"
}

### 기존 패스워드가 올바르지 않음
PUT http://localhost:8080/api/v1/account/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyLTAiLCJleHAiOjE3MDY3MDg4NTN9.PrWRaMnOGLJSdkC6nfT1XXSfMyznHHA1oeCeaxd9ItI

{
  "oldPassword": "pass",
  "newPassword": "password-1010"
}
