spring.config.activate.on-profile: prod

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${AWS_RDS_USERNAME}
    password: ${AWS_RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 50
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    web:
      pageable:
        one-indexed-parameters: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${OAUTH2_FACEBOOK_CLIENT_ID}
            client-secret: ${OAUTH2_FACEBOOK_CLIENT_SECRET}
            redirect-uri: 'https://waffle5gram.shop/login/oauth2/code/facebook'
            scope:
              - email
              - public_profile

cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: waffle5grambucket
    stack:
      auto: false

jwt:
  accessTokenSecretKey: ${JWT_ACCESS_TOKEN_SECRET_KEY}
  refreshTokenSecretKey: ${JWT_REFRESH_TOKEN_SECRET_KEY}
  ttlMinutesAccessToken: 5 # 5 minutes
  ttlMinutesRefreshToken: 360 # 6 hours
  refreshTokenCookieSecure: true
