spring.config.activate.on-profile: prod

spring:
  jpa:
    defer-datasource-initialization: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    web:
      pageable:
        one-indexed-parameters: true

cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: waffle5grambucket
    stack:
      auto: false
