server:
  port: 443
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: waffle5gram

spring.profiles.active: dev
spring:
  config:
    import:
    - application-dev.yaml
    - application-prod.yaml
