spring.config.activate.on-profile: dev-secure

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 348359328040767
            client-secret: 10f9eafe734151bcee983447aebf7d07
            scope:
              - email
              - public_profile
  data:
    web:
      pageable:
        one-indexed-parameters: true
