spring.config.activate.on-profile: dev-secure

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${OAUTH2_FACEBOOK_CLIENT_ID}
            client-secret: ${OAUTH2_FACEBOOK_CLIENT_SECRET}
            redirect-uri: 'https://waffle5gram.shop/login/oauth2/code/facebook'
            scope:
              - email
              - public_profile
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    web:
      pageable:
        one-indexed-parameters: true

cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: waffle5grambucket
    stack:
      auto: false

jwt:
  accessTokenSecretKey: ${JWT_ACCESS_TOKEN_SECRET_KEY}
  refreshTokenSecretKey: ${JWT_REFRESH_TOKEN_SECRET_KEY}
  ttlMinutesAccessToken: 360 # 6 hours
  ttlMinutesRefreshToken: 360 # 6 hours
  refreshTokenCookieSecure: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
