POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "username": "user-signup",
  "name": "Kim",
  "password": "test-password",
  "contact": "010-1111-9999",
  "contact_type": "phone",
  "birthday": "2000-12-15"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "user-0",
  "password": "password-0"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "waffle5",
  "password": "testPassword"
}
