POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "username": "user-signup",
  "name": "Kim",
  "password": "test-password",
  "contact": "010-1111-9999",
  "contactType": "phone",
  "birthday": "2000-12-15"
}

### 이미 존재하는 사용자명 사용
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "username": "user-0",
  "name": "Kim",
  "password": "test-password",
  "contact": "010-1111-9999",
  "contactType": "phone",
  "birthday": "2000-12-15"
}

### 유효하지 않은 contact_type
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "username": "test-user-150",
  "name": "Kim",
  "password": "test-password",
  "contact": "010-1111-9999",
  "contactType": "hello",
  "birthday": "2000-12-15"
}

### 유효하지 않은 이메일 형식
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "username": "test-user-160",
  "name": "Kim",
  "password": "test-password",
  "contact": "invalidEmail",
  "contactType": "email",
  "birthday": "2000-12-15"
}

### 유효하지 않은 전화번호 형식
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "username": "test-user-160",
  "name": "Kim",
  "password": "test-password",
  "contact": "88999000-000",
  "contactType": "phone",
  "birthday": "2000-12-15"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "user-0",
  "password": "password-0"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "waffle5",
  "password": "testPassword"
}
