name: CI/CD using github actions & docker including ktlint

# event trigger
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      # Test
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/actions/setup-java?tab=readme-ov-file#eclipse-temurin
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Check ktlint
        run: ./gradlew ktlintCheck

      - name: Build with Gradle
        if: github.event_name == 'push'
        run: ./gradlew build -x test

      # docker build & push
      - name: Docker build & push
        if: github.event_name == 'push'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/waffle5gram .
          docker push ${{ secrets.DOCKER_USERNAME }}/waffle5gram

      # deploy to EC2
      - name: Deploy
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          script: |
            sudo docker stop $(sudo docker ps -a -q)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/waffle5gram
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/waffle5gram
            sudo docker image prune -f

